version: '3'

services:
  php:
    image: lister:v2
    restart: always
    container_name: lister-php
    ports:
      - "81:80"
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      # MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flamy
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    # volumes:
      # - .:/var/www/html
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db